### ISSUE TITLE
Support for long cell titles

### ISSUE THREAD

**Issue by Davvie** [DavdRoman/Bohr#8] opened 2015-07-17 08:44 UTC
Bohr is great. But with the support (automatic resizing) of long cell titles it would become even better.

![2015-07-17 14 43 33](https://cloud.githubusercontent.com/assets/816045/8743647/e0458a62-2c89-11e5-9c29-b8d9aee65138.png)

**Comment by davdroman** [comment] 2015-07-17 18:29
That is definitely on my checklist. The thing is it's pretty tricky due to some Autolayout needs in certain cells. But yeah, I'm on working on it :)

**Comment by davdroman** [comment] 2015-07-31 13:12
So I've been trying to make it work but seems like storyboard's UITableViewControllers aren't quite ready for this kind of business.

I'll keep trying, but the idea of dropping storyboard support and make it all programmatic is growing in me. It's just much cleaner + allows for this kind of stuff.

What's your opinion on this?

**Comment by Davvie** [comment] 2015-08-07 09:55
Sorry for a late reply.

I believe you're right. Dropping storyboard support indeed gives more freedom.

There is a nice example of using a programmatic approach in a similar field. For instance, here's the way you can describe form fields in [FXForms](https://github.com/nicklockwood/FXForms):

``` objc
- (NSArray *)fields
{
    return @[
             @{FXFormFieldKey: @"email", FXFormFieldTitle: @"Email Address"},
             ...other fields...
            ];
}
```

I guess Bohr could benefit from using a similar approach by describing settings in code.

**Comment by davdroman** [comment] 2015-08-07 11:38
Good to hear your thoughts about this. I'll start working on v3 then :)

**Comment by davdroman** [comment] 2015-08-28 02:10
Hey there @Davvie!

I just pushed v3.0.0 alpha 1 and I'd like it if you gave it a try. I'm pretty positive this bug is now gone since the nasty Autolayout hack is now longer necessary :)

**Comment by Davvie** [comment] 2015-08-28 11:58
Great to hear version 3 is out! 

I tried to set it up but it doesn't seem to work at all :(

![1](https://cloud.githubusercontent.com/assets/816045/9545567/a5a21bf0-4da4-11e5-92c3-b8fb341e6865.png)

I guess, you've dropped Storyboard support. So I tried to do everything in code but I'm surely doing something wrong.

I've got a view controller which is a subclass of BOTableViewController. It is assigned to a storyboard scene.

The first and major problem is that setup() is never called.

That's how I tried to add settings to Bohr:

``` objc
BOTableViewSection *basicSettings = [[BOTableViewSection alloc] init];
    BOSwitchTableViewCell *autoLoginCell = [[BOSwitchTableViewCell alloc] init];
    autoLoginCell.textLabel.text = @"Automatic login";
    autoLoginCell.key = @"Settings_AutoLogin";
    BOSwitchTableViewCell *episodePriorityCell = [[BOSwitchTableViewCell alloc] init];
    episodePriorityCell.textLabel.text = @"Show new episodes first";
    episodePriorityCell.key = @"Settings_NewOnTop";
    [basicSettings addCell:autoLoginCell];
    [basicSettings addCell:episodePriorityCell];
    [self addSection:basicSettings];
```

**Comment by davdroman** [comment] 2015-08-28 16:40
Yeah storyboard support is _completely_ dropped, meaning not even assigning a subclass to a UITableViewController in a storyboard will work. I could include that little feature in next alpha if storyboards are really that mandatory.

Please try running the demo project on Xcode 7 :)

**Comment by Davvie** [comment] 2015-08-28 17:39
Aaah, I see. Well, in my current app I have a few buttons that initiate a storyboard segue. So having this little feature would be handy for me to migrate from v2 to v3 :)

But I think in my future projects I will anyway do everything settings-related just in code so it will be more extensible in the long run. Plus, sometimes it takes forever for Xcode to launch Interface Builder if the storyboard is complex.

I'm going to install Xcode 7 tomorrow, so I'll write back once I try it out :ok_hand:

**Comment by davdroman** [comment] 2015-08-28 17:43
I'll gladly implement it for alpha 2 then :smile:

**Comment by davdroman** [comment] 2015-08-28 22:53
Hey! I just released alpha 2. `BOTableViewController` should now be attachable as a class to storyboards' `UITableViewController`s.

**Comment by Davvie** [comment] 2015-08-29 11:01
Yay! Thank you for the Storyboard support, I've just moved to v3, so far so great :)

While running the demo project in Xcode 7 I encountered a few runtime error messages in the console:

`Aug 29 16:47:39  BohrDemo[50912] <Error>: CGContextSaveGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Aug 29 16:47:39  BohrDemo[50912] <Error>: CGContextTranslateCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Aug 29 16:47:39  BohrDemo[50912] <Error>: CGContextRestoreGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.`

![screen shot 2015-08-29 at 16 52 29](https://cloud.githubusercontent.com/assets/816045/9561634/0ce45054-4e67-11e5-9cdb-4859e19de7c7.png)

but the demo app itself works perfectly fine.

**Comment by davdroman** [comment] 2015-08-29 11:33
Hmm, that simulator screen is pretty weird. The text cell and footer title's font are bigger than they should be. Was it you who modified such values or is it a bug?

**Comment by Davvie** [comment] 2015-08-29 11:39
Oh, it does look weird. Haven't noticed it when I first took the screenshot.

No, I didn't change anything code-wise, just ran the project as it is.

**Comment by davdroman** [comment] 2015-08-29 11:53
Ok we have a few problems then. Let me install Xcode 7 myself and check out what's happening.

**Comment by davdroman** [comment] 2015-08-29 17:24
I've checked it out and seems like the problem with the text cell isn't ocurring for me, although footers are indeed displayed with a huge font size too. I'll work on that.

Do you see the text cell with the height displayed on the screenshot right when opening the app, or is it reproducible?

**Comment by Davvie** [comment] 2015-08-30 07:03
Just tried again, I can't seem to reproduce it. Tapped at all possible buttons and switches but everything's okay anyway.

Btw, noticed one minor issue while running in my current app (with Storyboard). If you start scrolling or changing settings the cells begin to resize (sometimes quite noticeably). But it happens only once.

**Comment by Davvie** [comment] 2015-08-30 12:32
Seems like there are some other iOS 9-related problems. Here's what happened when I tried to run my app: https://vid.me/Qx57

**Comment by davdroman** [comment] 2015-09-02 19:08
Alpha 4 is now up. Check it out. I think layout issues must be mostly gone :smile:

**Comment by Davvie** [comment] 2015-09-05 17:36
Great! Thank you, now I don't experience any layout issues at all :)

**Comment by davdroman** [comment] 2015-09-09 00:09
Cool! I'm closing this now :tada: 

Let me know if you run into any other issue.

**Closed as completed by davdroman** 2015-09-09 00:09 UTC
Labels: enhancement
